"""
Convert BT4-tf13tune.onnx to PyTorch using onnx2torch.
Generates:
  - bt4_model.pt (full converted PyTorch model)
  - bt4_forward_pass.py (the auto-generated forward pass code)
"""
import inspect
import onnx
import onnx2torch
import torch

ONNX_PATH = "leela_pytorch_impl/BT4-tf13tune.onnx"
OUT_MODEL = "leela_pytorch_impl/bt4_model.pt"
OUT_FORWARD = "leela_pytorch_impl/bt4_forward_pass.py"

print(f"Loading ONNX model from {ONNX_PATH}...")
onnx_model = onnx.load(ONNX_PATH)

# Print metadata
print("\nONNX Metadata:")
for prop in onnx_model.metadata_props:
    print(f"  {prop.key}: {prop.value}")

print("\nConverting to PyTorch with onnx2torch...")
pt_model = onnx2torch.convert(onnx_model)

print(f"\nSaving full model to {OUT_MODEL}...")
torch.save(pt_model, OUT_MODEL)

# Extract the generated forward pass code
print(f"\nExtracting forward pass code to {OUT_FORWARD}...")

# onnx2torch stores the generated code in various ways.
# Try to get the source from the model's code attribute or from the module.
source = None

# Method 1: Check for .code attribute on the model
if hasattr(pt_model, 'code'):
    source = pt_model.code
elif hasattr(pt_model, '_code'):
    source = pt_model._code

# Method 2: Try to get source from onnx2torch internals
if source is None:
    try:
        # onnx2torch may have stored the code during conversion
        import onnx2torch.node_converters as nc
        # Look for any generated code files
    except Exception:
        pass

# Method 3: Use inspect to get the source of the forward method
if source is None:
    try:
        source = inspect.getsource(pt_model.forward)
        source = f"def forward(self, input_1):\n{source[source.index('('):]}"
    except Exception as e:
        print(f"  Could not get source via inspect: {e}")

# Method 4: Use torch.jit to trace and inspect
if source is None:
    print("  WARNING: Could not extract generated forward pass code.")
    print("  The model is saved, but you'll need to use it via:")
    print("    model = torch.load('bt4_model.pt')")
    print("    output = model(input_tensor)")
else:
    header = '''"""Auto-generated forward pass for BT4-tf13tune model.
Generated by onnx2torch from BT4-tf13tune.onnx.

Architecture: AttentionBody with Smolgen
  - 15 encoder layers, 32 attention heads
  - Dmodel: 1024, Embedding: 1024, FFN DFF: 1536
  - Input: 112-plane classical with PE dense embedding
  - Activation: Mish (default), Swish (Smolgen)
  - Policy: Attention head, Value: WDL, MLH: Moves Left

Usage:
    model = torch.load('bt4_model.pt')
    output = model(input_tensor)
"""
'''
    with open(OUT_FORWARD, 'w') as f:
        f.write(header)
        f.write('\n')
        f.write(source)

    print(f"  Done! Forward pass saved to {OUT_FORWARD}")

# Test the model with a dummy input
print("\nTesting model with dummy input...")
# BT4 uses 112 input planes (no history)
dummy_input = torch.randn(1, 112, 8, 8)
pt_model.eval()
with torch.no_grad():
    output = pt_model(dummy_input)

print(f"  Output type: {type(output)}")
if isinstance(output, (tuple, list)):
    for i, o in enumerate(output):
        print(f"  Output[{i}] shape: {o.shape}")
elif isinstance(output, torch.Tensor):
    print(f"  Output shape: {output.shape}")
elif isinstance(output, dict):
    for k, v in output.items():
        print(f"  Output['{k}'] shape: {v.shape}")

print("\nDone!")
